### ISSUE TITLE
Cannot find atlas information; please download and unzip as follows...

### ISSUE THREAD

**Issue by seldamat** [neurodata/ndmg#163]
Running a pip installed ndmg on a bids dataset as such:

`ndmg_bids ~/ADS-DS/mris.bids $(pwd)/ndmg participant`

Crashed out with this error:
```
/Users/admin/miniconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Cannot find atlas information; please download and unzip as follows...
Source: s3://mrneurodata/data/resources/ndmg_atlases.zip
Destination: /ndmg_atlases
Traceback (most recent call last):
  File "/Users/admin/miniconda2/bin/ndmg_bids", line 11, in <module>
    sys.exit(main())
  File "/Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/scripts/ndmg_bids.py", line 268, in main
    session_level(inDir, outDir, subj, sesh, debug)
  File "/Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/scripts/ndmg_bids.py", line 115, in session_level
    assert(len(anat) == len(dwi))
AssertionError
```

Tried downloading the s3 file using `aws s3 cp` but I do not have creds, nor am I currently interested n making an aws account. Any ideas on how to proceed?

Thanks for your help

**Comment by gkiar** [comment]
Hi @seldamat - thanks for the note. To me, it looks like the error is actually after that. The atlases can be downloaded without credentials. The error is asserting that the number of diffusion and anatomical scans does not match - have you validated that all your sessions have each of: 1x T1w, 1x DWI, 1x Bval, and 1x Bvec? Unfortunately, ndmg is not currently sufficiently BIDS-aware that it'll use anatomical scans within subject but across sessions, if only 1 mprage was collected, for instance. Thanks!

**Comment by seldamat** [comment]
Ah yup, you're right - the bids validator gives me. I saw the len(anat)==len(dwi) statement but just ignored it 😅

	```
2: Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
		./sub-001/ses-001/anat/sub-001_ses-001_run-01_T1w.json
		./sub-001/ses-001/anat/sub-001_ses-001_run-01_T1w.nii.gz
		./sub-001/ses-001/anat/sub-001_ses-001_run-02_T1w.json
		./sub-001/ses-001/anat/sub-001_ses-001_run-02_T1w.nii.gz
		./sub-001/ses-001/anat/sub-001_ses-001_run-03_T1w.json
		./sub-001/ses-001/anat/sub-001_ses-001_run-03_T1w.nii.gz
		./sub-001/ses-001/func/sub-001_ses-001_task-emocountstroop_run-01_bold.json
		./sub-001/ses-001/func/sub-001_ses-001_task-emocountstroop_run-01_bold.nii.gz
		./sub-001/ses-001/func/sub-001_ses-001_task-emocountstroop_run-02_bold.json
		./sub-001/ses-001/func/sub-001_ses-001_task-emocountstroop_run-02_bold.nii.gz
		... and 15400 more files having this issue (Use --verbose to see them all).
```
I guess the best way around this is to run on a manually created list of subjects with complete data.

**Comment by seldamat** [comment]
Ok, so ran a subject specifically and crashed out at the alignment step because of a missing atlas. Can you recommend the best way to add the atlas files so that ndmg finds them? I'm assuming I should create an ndmg-atlases/atlas directory in the ndmg home dir and populate that with right files? How do I obtain these files?

```
ndmg_bids ~/ADS-DS/mris.bids $(pwd)/ndmg participant --participant_label 001 --session_label 001
/Users/admin/miniconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Cannot find atlas information; please download and unzip as follows...
Source: s3://mrneurodata/data/resources/ndmg_atlases.zip
Destination: /ndmg_atlases
T1 file: /Users/admin/ADS-DS/mris.bids/sub-001/ses-001/anat/sub-001_ses-001_T1w.nii.gz
DWI file: /Users/admin/ADS-DS/mris.bids/sub-001/ses-001/dwi/sub-001_ses-001_dwi.nii.gz
Bval file: /Users/admin/ADS-DS/mris.bids/sub-001/ses-001/dwi/sub-001_ses-001_dwi.bval
Bvec file: /Users/admin/ADS-DS/mris.bids/sub-001/ses-001/dwi/sub-001_ses-001_dwi.bvec
This pipeline will produce the following derivatives...
DWI volume registered to atlas: /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/reg/dwi/sub-001_ses-001_dwi_aligned.nii.gz
Diffusion tensors in atlas space: /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tensors/sub-001_ses-001_dwi_tensors.npz
Fiber streamlines in atlas space: /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/fibers/sub-001_ses-001_dwi_fibers.npz
Graphs of streamlines downsampled to given labels: /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/AAL/sub-001_ses-001_dwi_AAL.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/desikan/sub-001_ses-001_dwi_desikan.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/Desikan2012/sub-001_ses-001_dwi_Desikan2012.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/HarvardOxford/sub-001_ses-001_dwi_HarvardOxford.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/CPAC200/sub-001_ses-001_dwi_CPAC200.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/Talairach/sub-001_ses-001_dwi_Talairach.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/JHU/sub-001_ses-001_dwi_JHU.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/slab907/sub-001_ses-001_dwi_slab907.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/slab1068/sub-001_ses-001_dwi_slab1068.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00071/sub-001_ses-001_dwi_DS00071.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00096/sub-001_ses-001_dwi_DS00096.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00108/sub-001_ses-001_dwi_DS00108.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00140/sub-001_ses-001_dwi_DS00140.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00195/sub-001_ses-001_dwi_DS00195.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00278/sub-001_ses-001_dwi_DS00278.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00350/sub-001_ses-001_dwi_DS00350.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00446/sub-001_ses-001_dwi_DS00446.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00583/sub-001_ses-001_dwi_DS00583.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS00833/sub-001_ses-001_dwi_DS00833.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS01216/sub-001_ses-001_dwi_DS01216.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS01876/sub-001_ses-001_dwi_DS01876.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS03231/sub-001_ses-001_dwi_DS03231.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS06481/sub-001_ses-001_dwi_DS06481.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS16784/sub-001_ses-001_dwi_DS16784.edgelist, /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/graphs/DS72784/sub-001_ses-001_dwi_DS72784.edgelist
Generating gradient table...
B-values shape (80,)
         min 0.000000
         max 1100.000000
B-vectors shape (80, 3)
         min -0.996383
         max 0.994154
None
Aligning volumes...
Executing: eddy_correct /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tmp/sub-001_ses-001_dwi_t1.nii.gz /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tmp/sub-001_ses-001_dwi_t1_t2.nii.gz 0
Executing: epi_reg --epi=/Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tmp/sub-001_ses-001_dwi_t1_t2.nii.gz --t1=/Users/admin/ADS-DS/mris.bids/sub-001/ses-001/anat/sub-001_ses-001_T1w.nii.gz --t1brain=/Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tmp/sub-001_ses-001_T1w_ss.nii.gz --out=/Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tmp/sub-001_ses-001_dwi_t1_ta.nii.gz
Executing: flirt -in /Users/admin/ADS-DS/mris.bids/sub-001/ses-001/anat/sub-001_ses-001_T1w.nii.gz -ref /ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz -omat /Users/admin/miniconda2/lib/python2.7/site-packages/ndmg/ndmg/tmp/sub-001_ses-001_T1w_MNI152_T1_1mm_xfm.mat -dof 12 -bins 256 -cost mutualinfo -searchrx -180 180 -searchry -180 180 -searchrz -180 180
Error -6: Image Exception : #22 :: ERROR: Could not open image /ndmg_atlases/atlas/MNI152_T1_1mm
libc++abi.dylib: terminating with uncaught exception of type RBD_COMMON::BaseException
```

**Comment by jovo** [comment]
@loftusa *ingest* all the atlases using neuroglancer, send url to visualize them all on top of each other.  might need some help from @falkben

**Comment by jovo** [comment]
coordinate with @j1c to get the json/metadata
