### ISSUE TITLE
non-deterministic failure in functional branch

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#171]
Running the code in #164 (in the docker container `neurodata/m3r-release` converted to singularity on the fly), the following error pops up from time to time. Any idea what this is or why?

```
Traceback (most recent call last):
  File "/usr/local/bin/ndmg_bids", line 11, in <module>
    load_entry_point('ndmg==0.2.0', 'console_scripts', 'ndmg_bids')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/ndmg/__init__.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/ndmg/stats/func_qa_utils.py", line 29, in <module>
  File "/usr/local/lib/python2.7/dist-packages/plotly-1.12.1-py2.7.egg/plotly/__init__.py", line 31, in <module>
    from plotly import (plotly, graph_objs, grid_objs, tools, utils, session,
  File "/usr/local/lib/python2.7/dist-packages/plotly-1.12.1-py2.7.egg/plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "/usr/local/lib/python2.7/dist-packages/plotly-1.12.1-py2.7.egg/plotly/plotly/plotly.py", line 31, in <module>
    from plotly import exceptions, tools, utils, version, files
  File "/usr/local/lib/python2.7/dist-packages/plotly-1.12.1-py2.7.egg/plotly/tools.py", line 457, in <module>
    def mpl_to_plotly(fig, resize=False, strip_style=False, verbose=False):
  File "/usr/local/lib/python2.7/dist-packages/plotly-1.12.1-py2.7.egg/plotly/utils.py", line 331, in _decorator
    func.__doc__ = func.__doc__.format(**names)
KeyError: 'plotly_domain'
```

**Comment by ebridge2** [comment]
I believe this is addressed by https://github.com/neurodata/ndmg/commit/e96b69ab69b0cfae58b94fc79ba391370867b9ee ; not sure how to reproduce this error though.
