### ISSUE TITLE
group level analysis doesn't work on functional branch

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#173]
When running the container from #164, the group analysis doesn't run. This was attempted using the following command:

```
$ ndmg_bids ./bidsdir ./derivdir group dwi
Traceback (most recent call last):
  File "/usr/local/bin/ndmg_bids", line 11, in <module>
    load_entry_point('ndmg==0.2.0', 'console_scripts', 'ndmg_bids')()
  File "/usr/local/lib/python2.7/dist-packages/ndmg-0.2.0-py2.7-linux-x86_64.egg/ndmg/scripts/ndmg_bids.py", line 372, in main
  File "/usr/local/lib/python2.7/dist-packages/ndmg-0.2.0-py2.7-linux-x86_64.egg/ndmg/scripts/ndmg_bids.py", line 200, in group_level
NameError: global name 'modality' is not defined
```

**Comment by ebridge2** [comment]
https://github.com/neurodata/ndmg/commit/9fe1a144aa23dd14237c1d06acb3d3c450182554 fixed for dmri and fmri
