### ISSUE TITLE
installation error caused by DIPY

### ISSUE THREAD

**Issue by v715** [neurodata/ndmg#188]
I am creating a fresh installation of ndmg in the following way:

```
virtualenv -p /usr/bin/python2.7 ndmg
source ndmg/bin/activate
pip install ndmg
```

When I test the installation with the command `python -c 'from ndmg.utils import loadGraphs'`, I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vivek/Documents/GitHub/NDD/ndmg/lib/python2.7/site-packages/ndmg/__init__.py", line 10, in <module>
    from .scripts import ndmg_dwi_pipeline as ndmg_dwi_pipeline
  File "/Users/vivek/Documents/GitHub/NDD/ndmg/lib/python2.7/site-packages/ndmg/scripts/ndmg_dwi_pipeline.py", line 29, in <module>
    from ndmg.stats.qa_fibers import *
  File "/Users/vivek/Documents/GitHub/NDD/ndmg/lib/python2.7/site-packages/ndmg/stats/qa_fibers.py", line 29, in <module>
    from dipy.viz import window, actor
ImportError: cannot import name window
```

When I ran `pip freeze`, I noticed that fury (the package from which DIPY imports window and actor) was not installed. So I installed fury (`pip install fury`) and the ImportError went away. Can you guys reproduce this error and if so, should fury be added to `requirements.txt`?

I am running Python 2.7.10 on a macbook pro with macOS Mojave (version 10.14.2).

**Comment by ebridge2** [comment]
use the docker container or copy off the dockerfile; you'll probably be unsuccessful getting it installed on your laptop by yourself as there are many out-of-python dependencies
